### ISSUE TITLE
Binary release

### ISSUE THREAD

**Issue by nephaste** [jsimonetti/tlstun#1]
Hi your project look great, i wonder if i can provide your tool to Qnap NAS community

any chance to have binaries release ?

ARMV5 / V7
x86
x86_64

**Comment by jsimonetti** [comment]
Hi,

Feel free to use this any way you see fit. Inclusion of this app for the QNAP community sounds awesome.

I have added windows and linux amd64 binary releases. I don't have the setup to compile for arm unfortunately. When I have I will add them.

**Comment by jsimonetti** [comment]
@nephaste ARM binaries are added.
Let me know if you have any problems.

**Comment by nephaste** [comment]
Thanks a milion, but where can i find links ? dont find it on main project page

**Comment by nephaste** [comment]
oops got it on release page https://github.com/jsimonetti/tlstun/releases

thank i launch the qpkg dev

**Comment by nephaste** [comment]
just realized it miss the x86 (32bit) linux binaries, could you please add it
allowing to run tlstun on all plateform Intel based

**Comment by jsimonetti** [comment]
@nephaste I have also added linux x86 binaries.

**Comment by nephaste** [comment]
thanks a lot :)

**Comment by nephaste** [comment]
published : http://forum.qnap.com/viewtopic.php?f=320&t=119703
